# Generated by Django 3.2.16 on 2024-08-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20240813_2303"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "default_related_name": "posts",
                "ordering": ("-pub_date",),
                "verbose_name": "публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
    ]
